spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: book-service
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 1
            memory: 512Mi